apiVersion: v1
kind: ReplicationController
metadata:
  name: brc-standalone-$(.group)
spec:
  replicas: 1
  selector:
    name: brc-standalone-$(.group)
    mode: standalone
    provider: brc-$(.group)
  template:
    metadata:
      labels:
        name: brc-standalone-$(.group)
        mode: standalone
        provider: brc-$(.group)
        app: brc-standalone-$(.group)
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: brc-tls-secret-$(.group)
      containers:
      - name: brc-standalone-$(.group)
        image: quay.io/cafebazaar/booker-resources:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: /etc/secret-volume
        env:
          - name: BRC_LOG_LEVEL
            value: "DEBUG"
          - name: BRC_ELASTIC_URL
            value: "$(.elastic_url)"
          - name: BRC_CERT_FILE
            value: "/etc/secret-volume/tls.crt"
          - name: BRC_KEY_FILE
            value: "/etc/secret-volume/tls.key"
          - name: BRC_CA_FILE
            value: "/etc/secret-volume/tls.crt"
